### ISSUE TITLE
pyComtrade crashes when attempting to open a non cfg file.

### ISSUE THREAD

**Issue by ldemattos** [ldemattos/openComtradeViewer#10]
The program should be capable of defend itself from a malformed cfg file or from an attempt to read a non cfg file. However, I think it should be solved upstream https://github.com/miguelmoreto/pycomtrade .

Maybe I'll try a solution proposal and send a PR to @miguelmoreto .

**Comment by miguelmoreto** [comment]
@ldemattos I will wait for your PR!
Best regards,
Miguel

**Comment by ldemattos** [comment]
Problem solved within commit a10a529a7b4a22c631616869f0da4848c8c5197d
